import fs from 'fs';
import path from 'path';

// Describe the test statistics CloudTestHub stores after execution.
export interface TestResults {
  passed: number;
  failed: number;
  skipped: number;
}

// Recursively inspect Playwright's JSON report and count test outcomes.
function countResults(node: unknown): TestResults {
  // Return empty counts when the current JSON value is not an object.
  if (typeof node !== 'object' || node === null) {
    return {
      passed: 0,
      failed: 0,
      skipped: 0
    };
  }

  // Handle arrays by combining the results from every element.
  if (Array.isArray(node)) {
    return node.reduce<TestResults>(
      (total, item) => {
        const result = countResults(item);

        return {
          passed: total.passed + result.passed,
          failed: total.failed + result.failed,
          skipped: total.skipped + result.skipped
        };
      },
      {
        passed: 0,
        failed: 0,
        skipped: 0
      }
    );
  }

  // Treat the current value as a JSON object for recursive inspection.
  const object = node as Record<string, unknown>;

  // Count a Playwright test result based on its status field.
  if (
    typeof object.status === 'string' &&
    ['passed', 'failed', 'skipped'].includes(object.status)
  ) {
    return {
      passed: object.status === 'passed' ? 1 : 0,
      failed: object.status === 'failed' ? 1 : 0,
      skipped: object.status === 'skipped' ? 1 : 0
    };
  }

  // Recursively inspect nested properties for Playwright test results.
  return Object.values(object).reduce<TestResults>(
    (total, value) => {
      const result = countResults(value);

      return {
        passed: total.passed + result.passed,
        failed: total.failed + result.failed,
        skipped: total.skipped + result.skipped
      };
    },
    {
      passed: 0,
      failed: 0,
      skipped: 0
    }
  );
}

// Read Playwright's JSON report and return aggregated test statistics.
export function parsePlaywrightResults(): TestResults {
  // Locate the JSON report generated by Playwright.
  const resultsPath = path.resolve(
    process.cwd(),
    'test-results',
    'results.json'
  );

  // Fail clearly when Playwright did not generate the expected report.
  if (!fs.existsSync(resultsPath)) {
    throw new Error(`Playwright results not found: ${resultsPath}`);
  }

  // Read the generated JSON report from disk.
  const fileContent = fs.readFileSync(resultsPath, 'utf-8');

  // Convert the report text into a JavaScript object.
  const report = JSON.parse(fileContent);

  // Aggregate all test results found inside the report.
  return countResults(report);
}